# -*- coding: utf-8 -*-
"""open-cv-tutorial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1UBUJiVt5Ug4qRyrd7MXpzitoRI7f0OBU

**OpenCV **is an open-source software library for computer vision and machine learning. The OpenCV full form is Open Source Computer Vision Library.
"""
""""
import cv2 as cv 
img=cv.imread("C:\Users\osandal\Downloads\1.jpg")
cv.imshow('image',img)  
cv.waitKey()
cv.destroyAllWindows()

"""
import cv2 as cv

# Load the image
img = cv.imread(r"C:\Users\osandal\Downloads\1.jpg")

# Check if the image is loaded successfully
if img is None:
    print("Error: Failed to load image.")
    exit(1)

# Display the image
cv.imshow('image', img)
cv.waitKey(0)
cv.destroyAllWindows()
