# -*- coding: utf-8 -*-
"""Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rdWq8nOdgQGrX-OnCuhHKp8nrGKjnyiM
"""

!pip install pystan~=2.14

!pip install fbprophet

!pip install fbprophet

import pandas as pd
import matplotlib.pyplot as plt
from fbprophet import Prophet

data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Q1/monthly-car-sales (1).csv')
print(data)

plt.plot(data['Month'], data['Sales'])
plt.xlabel('Date')
plt.ylabel('Value')
plt.show()

test_data = data.tail(12)
train_data = data[:-12]
print(test_data)
print(train_data)

!pip install fbprophet

import pandas as pd
import matplotlib.pyplot as plt
from fbprophet import Prophet

data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Q1/monthly-car-sales (1).csv')
data['Month'] = pd.to_datetime(data['Month'])
data = data.sort_values('Month')


plt.plot(data['Month'], data['Sales'])
plt.xlabel('Date')
plt.ylabel('Value')
plt.show()

test_data = data.tail(12)
train_data = data[:-12]

test_data = test_data.rename(columns={'Month': 'ds', 'Sales': 'y'})
train_data = train_data.rename(columns={'Month': 'ds', 'Sales': 'y'})



model = Prophet()
model.fit(train_data)

forecast = model.predict(test_data)
forecast[['ds', 'yhat', 'yhat_lower', 'yhat_upper']].head()

plt.plot(test_data['ds'], test_data['y'], label='Actual')
plt.plot(forecast['ds'], forecast['yhat'], label='Predicted')
plt.xlabel('Months')
plt.ylabel('Sales')
plt.legend()
plt.show()

m = Prophet()
m.fit(train_data)
future = m.make_future_dataframe(periods=365)
forecast = m.predict(future)