# -*- coding: utf-8 -*-
"""4.1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ooNijPViUaCnlR_g2FGtmBI5iHClgdeH
"""

def is_power_of_three(n):
   
    if n <= 0:
        return False
    while n % 3 == 0:
        n = n // 3
    return n == 1

is_power_of_three(27)
is_power_of_three(4)

def collatz_conjecture(n):

    while n != 1:
        print(n, end=" ")
        if n % 2 == 0:
            n = n // 2
        else:
            n = 3 * n + 1
    print(n, end=" ")

collatz_conjecture(27)

def celsius_to_fahrenheit(celsius):
    fahrenheit = (celsius * 9/5) + 32
    return fahrenheit

celsius_to_fahrenheit(31)

def multiply_matrices(mat1, mat2):
    if len(mat1[0]) != len(mat2):
        print("Matrices cannot multiplied!")
        return None
    
    result = [[0 for j in range(len(mat2[0]))] for i in range(len(mat1))]

    for i in range(len(mat1)):
        for j in range(len(mat2[0])):
            for k in range(len(mat2)):
                result[i][j] += mat1[i][k] * mat2[k][j]
    
    return result

mat1=[[1,2,3],[1,2,3],[1,2,3]]
mat2 =[[1,2,3],[1,2,3],[1,2,3]]
multiply_matrices(mat1, mat2)

